# Generated by Django 4.2.7 on 2026-03-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_youtubeaccount_cookies_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubeaccount',
            name='cookies_txt',
            field=models.TextField(blank=True, default='', help_text='Paste Netscape-format cookies exported from your browser. Use "Get cookies.txt LOCALLY" (Chrome) or "cookies.txt" (Firefox). Visit youtube.com while signed in, then export cookies for youtube.com.'),
        ),
    ]
