# Generated by Django 4.2.7 on 2026-02-01 19:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("playlist_id", models.CharField(max_length=255, unique=True)),
                ("channel_id", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("video_count", models.IntegerField(default=0)),
                ("last_fetched", models.DateTimeField(auto_now=True)),
                ("total_duration", models.DurationField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stream",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=5000)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads/stream_thumbnails/"
                    ),
                ),
                ("stream_key", models.CharField(blank=True, max_length=255)),
                ("broadcast_id", models.CharField(blank=True, max_length=255)),
                ("stream_url", models.URLField(blank=True)),
                ("loop_enabled", models.BooleanField(default=True)),
                ("process_id", models.IntegerField(blank=True, null=True)),
                ("process_started_at", models.DateTimeField(blank=True, null=True)),
                ("last_heartbeat", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, max_length=1000)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
                ("playlist_videos", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("starting", "Starting"),
                            ("running", "Running"),
                            ("stopping", "Stopping"),
                            ("stopped", "Stopped"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="idle",
                        max_length=10,
                    ),
                ),
                (
                    "playlist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="streams",
                        to="streaming.playlist",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "youtube_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streams",
                        to="accounts.youtubeaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stream",
                "verbose_name_plural": "Streams",
            },
        ),
        migrations.CreateModel(
            name="StreamPlaylist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="streaming.playlist",
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="streaming.stream",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/media/")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads/thumbnails/"
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("video", "Video"), ("audio", "Audio")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("mime_type", models.CharField(blank=True, max_length=50)),
                ("sequence", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "duration",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(86400.0),
                        ],
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5368709120),
                        ],
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Media File",
                "verbose_name_plural": "Media Files",
            },
        ),
        migrations.CreateModel(
            name="StreamLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        default="INFO",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField(max_length=4096)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="streaming.stream",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stream Log",
                "verbose_name_plural": "Stream Logs",
                "indexes": [
                    models.Index(
                        fields=["stream", "level", "created_at"],
                        name="streaming_s_stream__4d2195_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="stream",
            index=models.Index(
                fields=["user", "status"], name="streaming_s_user_id_54ebe9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stream",
            index=models.Index(
                fields=["user", "created_at"], name="streaming_s_user_id_9ee386_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stream",
            index=models.Index(
                fields=["youtube_account", "status"],
                name="streaming_s_youtube_75019e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stream",
            index=models.Index(
                fields=["is_deleted", "user"], name="streaming_s_is_dele_f69e00_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stream",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_deleted", False), ("status__in", ["running", "starting"])
                ),
                fields=("youtube_account", "status"),
                name="unique_active_stream_per_channel",
            ),
        ),
        migrations.AddConstraint(
            model_name="stream",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "status__in",
                        ["idle", "starting", "running", "stopping", "stopped", "error"],
                    )
                ),
                name="valid_stream_status",
            ),
        ),
        migrations.AddIndex(
            model_name="mediafile",
            index=models.Index(
                fields=["user", "sequence"], name="streaming_m_user_id_b1cabf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediafile",
            index=models.Index(
                fields=["user", "created_at"], name="streaming_m_user_id_747365_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediafile",
            index=models.Index(
                fields=["user", "is_deleted"], name="streaming_m_user_id_d48cd0_idx"
            ),
        ),
    ]
