# Generated by Django 4.2.7 on 2026-02-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0002_stream_scheduling"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="stream",
            name="stream_scheduled_idx",
        ),
        migrations.AlterField(
            model_name="stream",
            name="status",
            field=models.CharField(
                choices=[
                    ("idle", "Idle"),
                    ("scheduled", "Scheduled"),
                    ("starting", "Starting"),
                    ("running", "Running"),
                    ("stopping", "Stopping"),
                    ("stopped", "Stopped"),
                    ("error", "Error"),
                ],
                db_index=True,
                default="idle",
                max_length=10,
            ),
        ),
    ]
