# Generated by Django 4.2.7 on 2026-02-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0003_remove_stream_stream_scheduled_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="media_files",
            field=models.ManyToManyField(
                blank=True, related_name="streams", to="streaming.mediafile"
            ),
        ),
    ]
